### ISSUE TITLE
Crash After Creation of Movie Barcode

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#208]
**Describe the bug**
VIAN crashed after trying to create movie barcode.

**Console Log**
Saving Project  has no job()
/Users/baflue/Documents/ERC_FilmColors/Analysetool/Korpus_Filme/1379_OneFromTheHeart_1981/1379_1_1_OneFromTheHeart_1981_DVD_VIAN
LOG:  Project Saved
Out of Bound
(<class 'OSError'>, OSError("Can't prepare for writing data (no appropriate function for conversion path)",), <traceback object at 0x1c500bd808>)
Traceback (most recent call last):
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/gui/main_window.py", line 1528, in analysis_result
    raise e
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/gui/main_window.py", line 1525, in analysis_result
    self.project.add_analysis(result)
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/container/project.py", line 527, in add_analysis
    analysis.set_project(self)
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/container/analysis.py", line 43, in set_project
    self.set_adata(self.data)
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/container/analysis.py", line 299, in set_adata
    self.project.hdf5_manager.dump(self.a_class().to_hdf5(d), self.a_class().dataset_name, self.unique_id)
  File "/Users/baflue/Documents/ERC_FilmColors/Analysetool/VIAN/vian/core/data/hdf5_manager.py", line 124, in dump
    self.h5_file[dataset_name][pos] = d
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/baflue/anaconda2/envs/vian-osx/lib/python3.5/site-packages/h5py/_hl/dataset.py", line 632, in __setitem__
    self.id.write(mspace, fspace, val, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 221, in h5py.h5d.DatasetID.write
  File "h5py/_proxy.pyx", line 132, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 93, in h5py._proxy.H5PY_H5Dwrite
OSError: Can't prepare for writing data (no appropriate function for conversion path)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Expected behavior**
Getting a movie barcode of 1379 One From the Heart

**Desktop (please complete the following information):**
 - OS: High Sierra
 - Browser Firefox
 
[1379_1_1_OneFromTheHeart_1981_DVD_VIAN.eext.zip](https://github.com/ghalter/VIAN/files/2749379/1379_1_1_OneFromTheHeart_1981_DVD_VIAN.eext.zip)

**Additional context**

**Comment by ghalter** [comment]
Moviebarcodes are completely removed from VIAN for now. 
However the segmentation acts now as a barcode
