### ISSUE TITLE
Crash During Segmentation Export / Compare Two Projects

### ISSUE THREAD

**Issue by flueko** [ghalter/VIAN#309]
**Describe the bug**
I tried to export a segmentation, and then VIAN crashed.

**Question**
What's the best  way to compare two projects?
[20200920-222834.txt](https://github.com/ghalter/VIAN/files/5253470/20200920-222834.txt)

Plaform:  darwin
Date:     20200920-222834.txt
Version:  0.8.16

#### Traceback ####

  File "core/gui/Dialogs/export_segmentation_dialog.py", line 79, in on_export
  File "core/data/exporters.py", line 188, in export

#### Exception ####

Traceback (most recent call last):
  File "core/gui/Dialogs/export_segmentation_dialog.py", line 79, in on_export
  File "core/data/exporters.py", line 188, in export
KeyError: 'start'

**Comment by ghalter** [comment]
This doesn't seem to be an issue anymore, further discussion about the project comparison is ongoing
